# Generated by Django 4.2.5 on 2023-10-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
